### ISSUE TITLE
Crashes every time

### ISSUE THREAD

**Issue by RememberBeats** [IgneButene/XTouch-FLStudio#5]
After 24h installing and uninstalling FL Studio and trying different versions of both FL and scripts I found the problem...

It crashes when using my other script (FL NILA) for the Komplete Kontrol M32 😢. I need both controllers working at the same time...

**With the previous version of the script running both works as intended**. Do you know where could be the problem? 

Script in question is: https://github.com/soundwrightpro/FRUITY-NILA

Your script is amazing, so sad I can't use both.

**Comment by IgneButene** [comment]
Hey!

Oh, that sucks. I don't think it would matter if it's a Mac.
I was initially having some issues like yourself, but then after fixing a
few things it started working.
Another few things. Can you try checking the information on View->Script
Output and send me a screenshot, please?
Also, have you got an extender? If so, there might be some issues I haven't
been able to test, since I don't own one, unfortunately.

Kind regards,
Igne

2023-10-31, an, 01:37 RememberBeats ***@***.***> rašė:

**Comment by RememberBeats** [comment]
Hey, I don't own the extender, just the X-Touch and NI KK m32.

Plus most of the things doesn't work as the manual says. Anyway I can keep using the previous one, clipin lights were already working.

This is the output from X-Touch.

FL Studio Midi scripting version: 30
"/Documents/Image-Line/FL Studio/Settings/Hardware/Behringer Touch FL (Octubre 23)/device_XTouch.py" found

init ok
OnInit ready
Traceback (most recent call last):
  File "<string>", line 684, in OnIdle
  File "<string>", line 580, in OnIdle
  File "/Documents/Image-Line/FL Studio/Settings/Hardware/Behringer Touch FL (Octubre 23)/mcu_base_class.py", line 126, in OnIdle
  File "<string>", line 509, in UpdateMsg
  File "/Documents/Image-Line/FL Studio/Settings/Hardware/Behringer Touch FL (Octubre 23)/mcu_device.py", line 90, in SetTextDisplay
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
